# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/level-up-advanced-python-3213390',
                'doc_host': 'https://miwojc.github.io',
                'git_url': 'https://github.com/miwojc/level-up-advanced-python-3213390',
                'lib_path': 'level_up_advanced_python_3213390'},
  'syms': { 'level_up_advanced_python_3213390.average_race_time': { 'level_up_advanced_python_3213390.average_race_time.get_average': ( 'average_race_time.html#get_average',
                                                                                                                                        'level_up_advanced_python_3213390/average_race_time.py'),
                                                                    'level_up_advanced_python_3213390.average_race_time.get_data': ( 'average_race_time.html#get_data',
                                                                                                                                     'level_up_advanced_python_3213390/average_race_time.py'),
                                                                    'level_up_advanced_python_3213390.average_race_time.get_rhines_times': ( 'average_race_time.html#get_rhines_times',
                                                                                                                                             'level_up_advanced_python_3213390/average_race_time.py')}}}
